### ISSUE TITLE
Getting TypeError: xArg.get() is not a function 

### ISSUE THREAD

**Issue by DK-06** [sqlite/sqlite-wasm#51]
I'm using Cordova application, With this tried to integrate your package to avoid websql access in browser. So I did the sample application which you provided in the documentary. It leads with the sqlite3 bootstrap initializerthrew: TypeError: xArg.get() is not a function. 

sqlite3ApiBootstrap() error: TypeError: xArg.get(...) is not a function 
at cache.xWrap.convertArgNoCheck (sqlite3-bundler-friendly.mjs:7752:68) 
at Object.sqlite3_vfs_find (sqlite3-bundler-friendly.mjs:7794:31) 
at sqlite3-bundler-friendly.mjs:10438:29
 at sqlite3-bundler-friendly.mjs:6773:13 
at Array.forEach (<anonymous>)
 at sqlite3ApiBootstrap (sqlite3-bundler-friendly.mjs:6772:44)
 at sqlite3-bundler-friendly.mjs:14355:32
 at callRuntimeCallbacks (sqlite3-bundler-friendly.mjs:666:26) 
at postRun (sqlite3-bundler-friendly.mjs:445:7) 
at doRun (sqlite3-bundler-friendly.mjs:5655:9)

And from catch block getting the below

TypeError: Cannot set properties of undefined (setting 'scriptInfo')
 at sqlite3-bundler-friendly.mjs:14417:22

Please provide any solution / sample application as soon as possible.

**Comment by tomayac** [comment]
For Cordova, please use any of the [officially recommended SQLite plugins](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html#sqlite-plugin). Thanks!
