### ISSUE TITLE
Error: Require is not defined

### ISSUE THREAD

**Issue by tianshuo** [sqlite/sqlite-wasm#82]
```
sqlite3-opfs-async-proxy.js:55 Uncaught 
ReferenceError: require is not defined
    at eval (sqlite3-opfs-async-proxy.js:55:1)
    at ./node_modules/.pnpm/@sqlite.org+sqlite-wasm@3.46.0-build2/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-opfs-async-proxy.js (node_modules_pnpm_sq…m_sq-19f42b.js:19:1)
    at __webpack_require__ (node_modules_pnpm_sq…_sq-19f42b.js:46:32)
    at node_modules_pnpm_sq…sq-19f42b.js:983:37
    at node_modules_pnpm_sq…sq-19f42b.js:985:12
./node_modules/.pnpm/@sqlite.org+sqlite-wasm@3.46.0-build2/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-opfs-async-proxy.js	@	node_modules_pnpm_sq…asm_sq-19f42b.js:19
__webpack_require__	@	node_modules_pnpm_sq…asm_sq-19f42b.js:46
(anonymous)	@	node_modules_pnpm_sq…sm_sq-19f42b.js:983
(anonymous)	@	node_modules_pnpm_sq…sm_sq-19f42b.js:985
Show 1 more frame
index.js??clonedRule…e=script&lang=js:16 Done initializing. Running demo...
sqlite3-worker1-bundler-friendly.mjs:55 Uncaught null
index.js??clonedRule…e=script&lang=js:18 Running SQLite3 version 3.46.0
app.js:19 Error SQLITE_ERROR: sqlite3 result code 1: no such vfs: opfs
```

This is  running  on Chrome Version126.0.6478.183 (x86_64) on Mac

Using the demo code:

```
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <HelloWorld msg="Welcome to Your Vue.js App"/>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import { sqlite3Worker1Promiser } from '@sqlite.org/sqlite-wasm';

const log = console.log;
const error = console.error;

const initializeSQLite = async () => {
  try {
    log('Loading and initializing SQLite3 module...');

    const promiser = await new Promise((resolve) => {
      const _promiser = sqlite3Worker1Promiser({
        onready: () => resolve(_promiser),
      });
    });

    log('Done initializing. Running demo...');

    const configResponse = await promiser('config-get', {});
    log('Running SQLite3 version', configResponse.result.version.libVersion);

    const openResponse = await promiser('open', {
      filename: 'file:mydb.sqlite3?vfs=opfs',
    });
    const { dbId } = openResponse;
    log(dbId);
    log(
      'OPFS is available, created persisted database at',
      openResponse.result.filename.replace(/^file:(.*?)\?vfs=opfs$/, '$1'),
    );
    // Your SQLite code here.
  } catch (err) {
    let newerr=!(err instanceof Error)? new Error(err.result.message):err;
    error(newerr.name, newerr.message);
  }
};

initializeSQLite();

export default {
  name: 'App',
  components: {
    HelloWorld
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

**Comment by tomayac** [comment]
This looks to me like a bundler issue with Webpack. The same code works fine in the [demo](https://github.com/sqlite/sqlite-wasm/blob/main/demo/wrapped-worker.js).
